apiVersion: apps/v1
kind: Deployment
metadata:
  name: geofilterservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geofilterservice
  template:
    metadata:
      labels:
        app: geofilterservice
    spec:
      containers:
        - name: geofilterservice
          image: yosepk/geofilterservice:latest