apiVersion: v1
kind: Service
metadata:
  name: geofilterservice-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: geofilterservice
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: geofilterservice
  sessionAffinity: None